export const EVENT = {
  COMPONENT_INITIALIZE: 'Component.initialize',
  ORDER_ADDED: 'ORDER_ADDED',
  ORDER_REMOVED: 'ORDER_REMOVED',
  ORDER_SUBMIT: 'ORDER_SUBMIT',
  ORDER_LIST_ITEM_REMOVED: 'ORDER_LIST_ITEM_REMOVED',
  CHANGE_OPTION: 'CHANGE_OPTION',
  SERVING: 'SERVING',
  SERVED: 'SERVED',
};
